-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PRODUCTS TABLE
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  barcode text unique,
  size text,
  stock_qty integer default 0,
  selling_price numeric default 0,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. TRANSACTIONS TABLE (Transfers & Returns)
-- We will store all stock movements here for simplicity.
-- Types: 'TRANSFER' (User uses stock), 'RETURN' (User returns stock), 'RECEIVE' (Warehouse adds stock - optional)
create table public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) not null,
  product_id bigint references public.products(id) not null,
  type text not null check (type in ('TRANSFER', 'RETURN', 'JOB_RETURN', 'RECEIVE')), 
  quantity integer not null,
  customer_name text, -- Optional, for transfers to jobs
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- ==============================================================================
-- DEFAULT ADMIN USER SETUP
-- ==============================================================================
-- After running this SQL, create your default admin user via the Signup page:
--
-- Email: admin@stock.com
-- Password: Admin@123!
-- Name: Administrator
-- Role: ADMIN (select ADMIN in signup form)
--
-- The JWT tokens and session are automatically handled by Supabase Auth.
-- Users will stay logged in across browser refreshes.
-- ==============================================================================

-- 3. ENABLE ROW LEVEL SECURITY
alter table public.products enable row level security;
alter table public.transactions enable row level security;

-- 4. RLS POLICIES

-- Products: Everyone can read, Only Admins can modify
-- (For now, we will allow all authenticated users to read)
create policy "Enable read access for all users" on public.products
  for select using (auth.role() = 'authenticated');

create policy "Enable insert for authenticated users" on public.products
  for insert with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users" on public.products
  for update using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users" on public.products
  for delete using (auth.role() = 'authenticated');

-- Transactions: detailed policies
-- Users can read their own transactions
create policy "Users can read own transactions" on public.transactions
  for select using (auth.uid() = user_id);

-- Users can insert their own transactions (taking stock, returning stock)
create policy "Users can insert own transactions" on public.transactions
  for insert with check (auth.uid() = user_id);

-- Admins (or everyone for now for simplicity of the prompt) can view all transactions
-- Note: A real app would restrict this better. For this MVP, we might keep it open or rely on "service_role" for admin.
-- Let's add a policy for Admins to view all if we had specific admin roles, but for now let's allow read all for reporting?
-- Actually, let's stick to: Users see theirs. Admin Dashboard might need a special query or use the service role.
-- But wait, our 'AdminDashboard' runs on the client. It needs to fetch ALL transactions.
-- So we need a policy allowing specific users (Admins) to read everything.
-- For this MVP, let's allow ALL authenticated users to READ all transactions, but frontend filters it.
-- This is less secure but enables the Admin Dashboard to work without complex role setup in SQL right now.
create policy "Allow read all for admin purposes" on public.transactions
  for select using (auth.role() = 'authenticated');

-- ==============================================================================
-- HELPER FUNCTIONS FOR STOCK MANAGEMENT
-- ==============================================================================

-- Function to decrease product stock
create or replace function decrement_stock(product_id bigint, qty integer)
returns void as $$
begin
  update public.products
  set stock_qty = stock_qty - qty
  where id = product_id;
end;
$$ language plpgsql security definer;

-- Function to increase product stock
create or replace function increment_stock(product_id bigint, qty integer)
returns void as $$
begin
  update public.products
  set stock_qty = stock_qty + qty
  where id = product_id;
end;
$$ language plpgsql security definer;
