-- ============================================================================
-- COMPLETE SUPABASE BACKEND SETUP
-- Run this entire script in Supabase SQL Editor
-- ============================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- 1. CREATE TABLES
-- ============================================================================

-- PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text,
  barcode text UNIQUE,
  size text,
  stock_qty integer DEFAULT 0,
  buying_price numeric DEFAULT 0,
  selling_price numeric DEFAULT 0,
  image_url text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- TRANSACTIONS TABLE (Transfers & Returns)
CREATE TABLE IF NOT EXISTS public.transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) NOT NULL,
  product_id bigint REFERENCES public.products(id) NOT NULL,
  type text NOT NULL CHECK (type IN ('TRANSFER', 'RETURN', 'JOB_RETURN', 'RECEIVE')),
  quantity integer NOT NULL,
  customer_name text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================================
-- 2. ENABLE ROW LEVEL SECURITY
-- ============================================================================

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 3. RLS POLICIES
-- ============================================================================

-- Products: All authenticated users can read/write (simplified for MVP)
DROP POLICY IF EXISTS "Enable read access for all users" ON public.products;
CREATE POLICY "Enable read access for all users" ON public.products
  FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.products;
CREATE POLICY "Enable insert for authenticated users" ON public.products
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.products;
CREATE POLICY "Enable update for authenticated users" ON public.products
  FOR UPDATE USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.products;
CREATE POLICY "Enable delete for authenticated users" ON public.products
  FOR DELETE USING (auth.role() = 'authenticated');

-- Transactions: Users can access their own, all users can read all (for admin dashboard)
DROP POLICY IF EXISTS "Users can read own transactions" ON public.transactions;
CREATE POLICY "Users can read own transactions" ON public.transactions
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own transactions" ON public.transactions;
CREATE POLICY "Users can insert own transactions" ON public.transactions
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow read all for admin purposes" ON public.transactions;
CREATE POLICY "Allow read all for admin purposes" ON public.transactions
  FOR SELECT USING (auth.role() = 'authenticated');

-- ============================================================================
-- 4. STOCK MANAGEMENT FUNCTIONS
-- ============================================================================

-- Function to decrease product stock
CREATE OR REPLACE FUNCTION decrement_stock(product_id bigint, qty integer)
RETURNS void AS $$
BEGIN
  UPDATE public.products
  SET stock_qty = stock_qty - qty
  WHERE id = product_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to increase product stock
CREATE OR REPLACE FUNCTION increment_stock(product_id bigint, qty integer)
RETURNS void AS $$
BEGIN
  UPDATE public.products
  SET stock_qty = stock_qty + qty
  WHERE id = product_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- 5. USER MANAGEMENT FUNCTION
-- ============================================================================

-- Function to get all users (for admin dropdown)
CREATE OR REPLACE FUNCTION get_all_users()
RETURNS TABLE (
  id uuid,
  email text,
  name text,
  role text,
  created_at timestamptz
) 
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    au.id,
    au.email::text,  -- Cast varchar to text
    COALESCE(au.raw_user_meta_data->>'name', split_part(au.email, '@', 1))::text as name,
    COALESCE(au.raw_user_meta_data->>'role', 'USER')::text as role,
    au.created_at
  FROM auth.users au
  ORDER BY au.created_at DESC;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- 6. INDEXES FOR PERFORMANCE
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_products_barcode ON public.products(barcode);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON public.transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_product_id ON public.transactions(product_id);
CREATE INDEX IF NOT EXISTS idx_transactions_type ON public.transactions(type);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON public.transactions(created_at DESC);

-- ============================================================================
-- SETUP COMPLETE!
-- ============================================================================
-- 
-- Next steps:
-- 1. Enable Email authentication in Supabase Dashboard (Authentication → Providers)
-- 2. Disable email confirmations for testing (Authentication → Settings)
-- 3. In your app, go to Signup page and create admin user:
--    - Email: admin@stock.com
--    - Password: Admin@123!
--    - Name: Administrator
--    - Role: ADMIN (select from dropdown, then remove the dropdown from signup)
--
-- ============================================================================
